"""Migracao inicial

Revision ID: f7c5e8877e90
Revises: 
Create Date: 2024-02-29 22:17:58.570220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c5e8877e90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_categorias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('dta_cadastro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('dta_atualizada', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_produtos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('preco', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('dta_cadastro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('dta_atualizada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['tbl_categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_produtos')
    op.drop_table('tbl_categorias')
    # ### end Alembic commands ###
